## Tensor

딥러닝을 하다보면 Tensor라는 개념이 많이 나올 것이다.

그 중 Tensor의 개념을 잘 이해하는 것이 중요한데,

딥러닝에서는 주로 고차원적인 데이터를 많이 사용될 것이기 때문

Numpy는 그런 고차원적인 데이터를 다루기 쉽게 만들어져 있어 딥러닝을 하시게 된다면 늘 접하게 될 것임

Numpy를 통해 간단하게만 이해하도록 하자

In [1]:
import numpy as np

## 0차원

In [4]:
arr = np.array(5)
arr.shape

()

Scalar로 들어갔을 때는 shape가 아무것도 없는 것으로 나온다

In [5]:
arr.ndim

0

## 1차원 

1. 숫자가 10과 같이 하나만 들어간다고 해도 [] 리스트를 한 번 씌우게 되면 차원이 생긴다.
2. 이때는 1차원이 되는건데 numpy에서 shape를 표현할 때 (1)이 아닌 (1, ) 이런 식으로 표현하게 됨

In [8]:
arr = np.array([5])
arr.shape

(1,)

In [9]:
arr

array([5])

3. 명심해야 할 것이 있는데 (3, )에서 3은 3이라는 값이 들어간 것이 아니라 shape라는 것을 명심
4. 1차원에 3개의 값이 들어갔다는 의미
5. 해석하자면 1차원에 3개의 값(value)가 들어감

In [11]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [12]:
arr.shape

(3,)

## 2차원 

대괄호를 추가적으로 씌우면 차원이 추가적으로 하나 생김

In [13]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [14]:
arr.shape

(1, 3)

위의 shape를 다시 보자면 차원이 2개가 있고, 각 차원 마다 각각 3개의 값이 들어있다고 생각하면 됨

In [16]:
arr = np.array([[1,2,3], [1,2,3], [1,2,3]])
arr.shape

(3, 3)

참고로 0차원 숫자에 대괄호에 대괄호를 2번 씌우면 두개의 차원이 됨

In [17]:
np.array([10])

array([10])

In [18]:
arr = np.array([[10]])
arr.shape

(1, 1)

In [19]:
arr.ndim

2

## 다차원 

In [21]:
arr = np.array([[[[1,2,3,],[1,2,3,],[1,2,3,]],[[1,2,3,],[1,2,3,],[1,2,3,]],[[1,2,3,],[1,2,3,],[1,2,3,]]],[[[1,2,3,],[1,2,3,],[1,2,3,]],[[1,2,3,],[1,2,3,],[1,2,3,]],[[1,2,3,],[1,2,3,],[1,2,3,]]],[[[1,2,3,],[1,2,3,],[1,2,3,]],[[1,2,3,],[1,2,3,],[1,2,3,]],[[1,2,3,],[1,2,3,],[1,2,3,]]]])
arr.shape

(3, 3, 3, 3)

In [22]:
arr

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])