## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [2]:
import numpy as np
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
zeros = np.zeros(1)
zeros

array([0.])

In [5]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [8]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [9]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [11]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Index 

In [18]:
nums = [1,2,3,4,5]

In [19]:
nums[2:]

[3, 4, 5]

In [20]:
nums = [1,2,3,4,[1,2,3]]

In [21]:
nums

[1, 2, 3, 4, [1, 2, 3]]

In [22]:
nums[4]

[1, 2, 3]

In [16]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr[1]

array([3, 4, 5])

In [24]:
arr[1][-1]

5

In [25]:
arr[1,-1]

5

## Slicing 

In [26]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr[2:]

array([[6, 7, 8]])

In [28]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [29]:
arr[1:,1:]

array([[4, 5],
       [7, 8]])

## Boolean Indexing 

In [31]:
data = np.random.randn(3,3)
data

array([[ 1.29656608,  0.51479681, -0.81419768],
       [-0.28273366, -0.35668901, -1.0281241 ],
       [-0.89668446,  1.44693171,  0.32406106]])

In [32]:
data <= 0

array([[False, False,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [33]:
data[data <= 0]

array([-0.81419768, -0.28273366, -0.35668901, -1.0281241 , -0.89668446])

In [34]:
data[data <= 0] = 1

In [35]:
data

array([[1.29656608, 0.51479681, 1.        ],
       [1.        , 1.        , 1.        ],
       [1.        , 1.44693171, 0.32406106]])

## Broadcast 

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두 개의 행렬의 shape가 같지 않고,

한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때

이를 여러 복사를 하여 연산을 함

In [36]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [39]:
arr + np.array([1,1,1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function 

In [41]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [43]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [44]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [47]:
np.add(arr,1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [50]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [51]:
arr = np.random.randint(2, size = 27).reshape(3,3,3)
arr_2 = np.random.randint(2, size = 9).reshape(3,3)

In [52]:
arr

array([[[1, 1, 1],
        [1, 1, 0],
        [1, 0, 0]],

       [[0, 1, 1],
        [1, 1, 1],
        [1, 0, 0]],

       [[0, 0, 0],
        [1, 0, 0],
        [1, 0, 1]]])

In [53]:
arr_2

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [54]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [56]:
arr + arr_2

array([[[1, 2, 1],
        [1, 1, 1],
        [1, 0, 1]],

       [[0, 2, 1],
        [1, 1, 2],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [1, 0, 2]]])

In [57]:
arr * arr_2

array([[[0, 1, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]]])

In [58]:
np.sum(arr)

15

In [59]:
np.sum(arr_2)

3

In [60]:
np.sum(arr+arr_2)

24

In [61]:
np.max(arr)

1

In [62]:
np.max(arr_2)

1

In [63]:
np.max(arr+arr_2)

2

In [64]:
np.min(arr)

0

In [65]:
np.min(arr_2)

0

In [66]:
np.min(arr+arr_2)

0

In [67]:
np.max(arr+arr_2, 0)

array([[1, 2, 1],
       [1, 1, 2],
       [1, 0, 2]])

In [68]:
arr+arr_2

array([[[1, 2, 1],
        [1, 1, 1],
        [1, 0, 1]],

       [[0, 2, 1],
        [1, 1, 2],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [1, 0, 2]]])

In [75]:
np.sum(arr+arr_2, axis = 0)

array([[1, 5, 2],
       [3, 2, 4],
       [3, 0, 4]])

In [69]:
np.sum(arr+arr_2, 0)

array([[1, 5, 2],
       [3, 2, 4],
       [3, 0, 4]])

In [70]:
np.sum(arr+arr_2, 1)

array([[3, 3, 3],
       [2, 3, 4],
       [2, 1, 3]])

In [72]:
np.sum(arr+arr_2, 2)

array([[4, 3, 2],
       [3, 4, 2],
       [1, 2, 3]])

In [73]:
np.sum(arr+arr_2, -1)

array([[4, 3, 2],
       [3, 4, 2],
       [1, 2, 3]])

In [76]:
np.mean(arr)

0.5555555555555556

In [77]:
arr = np.array([1,6,3,7,3,2,9])
arr

array([1, 6, 3, 7, 3, 2, 9])

In [79]:
np.argmax(arr) #가장 큰 값의 인덱스

6

In [80]:
np.argmin(arr)

0

In [81]:
arr = np.array([3,5,6,6,3,3,1])

In [82]:
np.unique(arr)

array([1, 3, 5, 6])