## Numpy Basic 

In [1]:
import numpy as np

## data type 

array의 dtype을 본다. 

In [2]:
arr = np.array([[1,2,3],[1,2,3]])

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr = np.array([[1.,2,3],[1,2,3]])

In [5]:
arr.dtype

dtype('float64')

.astype()으로 datatype을 변환 가능

In [6]:
arr.astype('float32')

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [7]:
arr.astype('int32')

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
arr.astype(np.uint8)

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

In [10]:
arr.dtype

dtype('float64')

In [12]:
arr = arr.astype(np.int32)

In [13]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [14]:
arr.shape

(2, 3)

In [16]:
arr.dtype

dtype('int32')

In [18]:
arr = np.array([[1,2,3],[1,2,3]], dtype = np.uint8)
arr.dtype

dtype('uint8')

len(arr.shape)를 통해 차원의 갯수를 확인할 수 있지만,
아래와 같이 ndim을 통해 차원 수를  return 가능

In [19]:
arr.ndim

2

In [20]:
len(arr.shape)

2

size 확인

In [21]:
arr.size

6

dtype 확인

In [22]:
arr.dtype

dtype('uint8')

## Reshape 

In [23]:
arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

In [24]:
arr.shape

(2, 3)

Reshape

In [26]:
arr.reshape([1,6])

array([[1, 2, 3, 1, 2, 3]], dtype=uint8)

In [27]:
arr.shape

(2, 3)

In [28]:
arr = arr.reshape([1,6])
arr.shape

(1, 6)

In [30]:
arr = np.array([[1,2,3],[1,2,3]])

In [31]:
arr.shape

(2, 3)

In [32]:
arr_1 = arr.reshape([6])
arr_1

array([1, 2, 3, 1, 2, 3])

In [33]:
arr_1.shape

(6,)

Reshape, -1 활용

In [34]:
arr = np.array([[1,2,3],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [35]:
arr.reshape(-1)

array([1, 2, 3, 1, 2, 3])

In [37]:
arr.reshape(1,-1) # -1은 남는 거! 예) size가 6이라면 (1,2,3), (2,3) 등이 가능한데 (-1.2.3), (-1.3)이면 이때 -1은 각각 1, 2이다.

array([[1, 2, 3, 1, 2, 3]])

random array 생성

In [39]:
arr = np.random.randn(8,8)
arr.shape

(8, 8)

In [40]:
arr = arr.reshape([32,2])
arr.shape

(32, 2)

3차원으로 늘리기

In [41]:
arr = arr.reshape([-1,2,1])
arr.shape

(32, 2, 1)

## Ravel

In [42]:
arr.shape

(32, 2, 1)

In [44]:
arr = arr.ravel()
arr

array([-0.76576868,  0.40572371, -0.04024032, -0.68614386,  0.92550073,
       -1.89148517, -0.92151538, -0.07817471,  0.22029866, -1.56828268,
       -0.28556526, -0.24352845, -1.12039975,  1.67245773, -1.89331801,
        0.02707569,  0.18083177,  0.06664516,  0.19098382,  0.7380592 ,
        0.42460734, -0.21658416,  1.06021084,  0.50782353,  0.28835996,
       -0.28695798, -0.34754742, -1.04884532,  0.58699197, -0.76329899,
       -0.31290897,  0.60280329, -0.15743331,  0.16652033,  0.42227203,
       -0.00302445,  0.53614108,  0.79891668,  1.22330985, -1.55168523,
       -0.14215227, -0.82199786, -1.86622621,  0.46672524,  0.29493339,
       -0.48499377,  0.19470061,  1.66917719,  2.07022626,  0.26809276,
       -0.74657426,  1.07366398, -1.06909917,  0.53114796,  1.47121881,
       -1.30723376,  1.15371127,  0.15859631, -0.51316429, -0.63821338,
        1.62030226,  0.35527394, -1.17473157, -0.3728693 ])

In [45]:
arr.shape

(64,)

arr의 차원을 1차로 바꿔줌

나중에 배울 layer를 flatten 할 때 같은 기능이라고 생각하면 됨

arr.reshape(-1) 와 같음

In [47]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음

이럴 때 사용하는 것이 expand_dims()

In [60]:
arr = np.random.randn(8,8)
arr = arr.reshape(-1)
arr.shape

(64,)

In [61]:
arr.shape

(64,)

In [62]:
arr = np.expand_dims(arr, 0)
arr.shape

(1, 64)

In [63]:
arr = arr.ravel()

In [64]:
arr = np.expand_dims(arr,-1)
arr.shape

(64, 1)

In [65]:
arr = arr.ravel()
arr.shape

(64,)

In [66]:
arr = np.expand_dims(np.expand_dims(arr,-1),0)
arr.shape

(1, 64, 1)